from typing import Protocol

from app.domain.auth import AuthCode, RefreshToken
from app.domain.patient import Patient
from app.domain.user import User


class UserStore(Protocol):
    def save(self, user: User) -> None: ...
    def get(self, user_id: str) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def get_by_employee_id(self, employee_id: str) -> User | None: ...


class AuthCodeStore(Protocol):
    def save(self, code: AuthCode) -> None: ...
    def consume(self, code: str) -> AuthCode | None: ...


class RefreshTokenStore(Protocol):
    def save(self, token: RefreshToken) -> None: ...
    def get(self, token: str) -> RefreshToken | None: ...
    def revoke(self, token: str) -> None: ...


class PatientStore(Protocol):
    def save_all(self, patients: list[Patient]) -> None: ...
    def list_by_employee(self, employee_id: str) -> list[Patient]: ...
